### ISSUE TITLE
Feature proposal: Editing components using drag and drop

### ISSUE THREAD

**Issue by vasco3** [crcn/tandem-old#403]
Would be very helpful to implement drag and drop in the renderer. So the experience would be more like using Sketch, when the developer is designing using mostly the mouse.
Bubble.is has achieved this although I don't know how clean their output code is.

**Comment by crcn** [comment]
Yeah, I think this is a great idea, especially having the ability to register your own components. This could totally work for template-based frameworks such as Angular & Vue. 

I'm not so concerned about code quality output since developers can easily modify any code that Tandem produces.

**Comment by tomByrer** [comment]
+1, since I'm looking at this to replace [Webydo](https://vimeo.com/60081222), ukit.com & Weebly.

> I'm not so concerned about code quality output since developers can easily modify any code that Tandem produces.

There could be a point where it would be easier just to write by hand, so I wouldn't make it too janky.   Code efficiency is very important to me since it can affect time-to-glass on mobile.

I quit Weebly because of div-itis.  & oh layout was in `<table>s`.  But the worst was the 'custom code' box, which was a div containing a div containing a div containing an *iframe*....

**Comment by vasco3** [comment]
I'm excited about https://protoship.io/tools/uipad.html 
they advertise Sketch to React

**Comment by crcn** [comment]
Closing this ticket in favor if #422. I'm currently working on this feature for Alpha. 🎉
