### ISSUE TITLE
Use docker for development

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#405]
Instead of requiring NPM / NodeJS, use Docker as an isolated environment so that developers don't have any issue with setting up Tandem on their local machine.

**Comment by pfurini** [comment]
Hi, the most common solutions for that are indeed:

- Docker with docker-compose (a single `docker-compose up -d` command does the job)
- Vagrant (here it's just `vagrant up`)

If possibile, I'll have both for the sake of choice.. ;)

**Comment by pfurini** [comment]
..but.. if the problem is only in getting a specific version of node/npm, a simple solution is to use a couple of tools like https://direnv.net and https://github.com/wilmoore/nodejs-install, with a setup script to run after cloning.

These are the two files I use in my node repos (one setup and one .envrc file for `direnv` tool)
https://gist.github.com/pfurini/abf1298d8dabd1c3e91aaf9c11ac98de

Hope this helps!

PS: only tested on *nix boxes, win users are not my main concern.. :-P

**Comment by crcn** [comment]
This shouldn't be an issue anymore since Electron is no-longer used. Closing for now.
